### ISSUE TITLE
'SkeletonLoading' cannot be used as a JSX component. Its type 'typeof import("MY_APP/node_modules/expo-skeleton-loading/index")' is not a valid JSX element type.ts(2786)

### ISSUE THREAD

**Issue by Deval99** [mmusaib/expo-skeleton-loading#1]
Steps to reproduce

installed the plugin
`npm install expo-skeleton-loading --save`

babel.config.js
`
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin']
};
`

import the component
`import SkeletonLoading from 'expo-skeleton-loading'`

use the component in tsx
`
<SkeletonLoading background={"#adadad"} highlight={"#ffffff"}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <View style={{ width: 100, height: 100, backgroundColor: "#adadad", borderRadius: 10 }} />
          <View style={{ flex:1, marginLeft: 10 }}>
              <View style={{ backgroundColor: "#adadad", width: "50%", height: 10, marginBottom: 3, borderRadius: 5 }} />
              <View style={{ backgroundColor: "#adadad", width: '20%', height: 8, borderRadius: 5 }} />
              <View style={{ backgroundColor: "#adadad", width: '15%', height: 8, borderRadius: 5, marginTop: 3 }} />
          </View>
        </View>
    </SkeletonLoading>
`
    
Issue:
- JSX element type 'SkeletonLoading' does not have any construct or call signatures.ts(2604)

- 'SkeletonLoading' cannot be used as a JSX component. Its type 'typeof import("MY_APP/node_modules/expo-skeleton-loading/index")' is not a valid JSX element type.ts(2786)

Versions used: 
"expo": "^50.0.17",
"react-native": "0.73.7",
"expo-skeleton-loading": "^1.0.3",

**Comment by karel-suchomel** [comment]
Use this patch file:

```
diff --git a/node_modules/expo-skeleton-loading/index.d.ts b/node_modules/expo-skeleton-loading/index.d.ts
deleted file mode 100644
index c312c70..0000000
--- a/node_modules/expo-skeleton-loading/index.d.ts
+++ /dev/null
@@ -1,12 +0,0 @@
-
-export interface SkeletonLoading {
-    /**
-     * background of the loader componenet
-     */
-    background: string,
-
-    /**
-     * highlight color of the loader component
-     */
-    highlight: string
-}
\ No newline at end of file
diff --git a/node_modules/expo-skeleton-loading/index.tsx b/node_modules/expo-skeleton-loading/index.tsx
index 819d63d..e8a774a 100644
--- a/node_modules/expo-skeleton-loading/index.tsx
+++ b/node_modules/expo-skeleton-loading/index.tsx
@@ -1,5 +1,5 @@
-import React from "react";
-import { View, StyleSheet } from "react-native";
+import React, { ReactElement } from "react";
+import { View, StyleSheet, LayoutRectangle } from "react-native";
 import MaskedView from "@react-native-masked-view/masked-view";
 import { LinearGradient } from "expo-linear-gradient";
 import Reanimated,{ useSharedValue, withRepeat, useAnimatedStyle, withTiming, interpolate  } from "react-native-reanimated";
@@ -15,6 +15,7 @@ interface SkeletonProps {
      * highlight color of the loader component hexcode
      */
     highlight: string
+    children: ReactElement
 }
 
 
@@ -24,7 +25,7 @@ const SkeletonLoading: React.FC<SkeletonProps> = ({
         highlight 
 }) => {
 
-    const [layout, setLayout] = React.useState();
+    const [layout, setLayout] = React.useState<LayoutRectangle>();
     const shared = useSharedValue(0);
 
     const animStyle = useAnimatedStyle(() => {
```

**Comment by netronicus** [comment]
same issue for me

**Comment by mmusaib** [comment]
Fixed the issue. Please try the latest version of the package.

Do inform me if you face any issue

**Comment by enisit** [comment]
Facing the same issue with latest `1.0.5` version @mmusaib 
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/505fcd76-6429-4c2b-a8d3-db893067397b">

**Comment by mmusaib** [comment]
It is just the warning thrown by linter. It is not an error. You can easily run the script.

**Comment by mmusaib** [comment]
@enisit You can either turn off the linter, or you can additionally disable the warning in the linter config files.

Hope I have helped with my answer :)

**Comment by CesarAugusto316** [comment]
this worked well for me:  
`
import Skeleton, { SkeletonLoading } from 'expo-skeleton-loading';
const MySkeleton = Skeleton as FC<SkeletonLoading & { children: ReactNode }>;

`
